spring:
  datasource:
    url: jdbc:h2:mem:tododb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

server:
  error:
    include-message: always

logging.logstash:
  enabled: false
  url: localhost:5000

logging:
  file:
    name:
