spring:
  datasource:
    url: jdbc:h2:mem:tododb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

server:
  error:
    include-message: always
